### ISSUE TITLE
The key names of the parsed connection string  object are not in camelCase

### ISSUE THREAD

**Issue by mjordang** [tediousjs/connection-string#30]
Hello, this is more a suggestion that an issue, the object generated  after the parse does not have the key names in camelCase (ex: "user id","initial catalog", "data source")  , which is the most widespread and used javaScript code 
convention. 

``{
  "user id": "user",
  "password": "password",
  "initial catalog": "AdventureWorks",
  "data source": "MySqlServer"
}``

I think that to do an improvement to convert to camelCase the keys would facilitate the use of the library in the standards.

For more info, see JavaScript code conventions: https://www.w3schools.com/js/js_conventions.asp.

Thanks.

**Comment by dhensby** [comment]
Hey, thanks for the suggestion. I'm not sure there's any value in implementing that change as it's just stylistic and for not much gain. The idea is to represent the connection string as a normalised dictionary.

If you want camelCase in your usage, running the output through a basic reducer can turn the object into one with camelCased keys.
