### ISSUE TITLE
Support for URI type connection string

### ISSUE THREAD

**Issue by mstrujic-cls** [tediousjs/connection-string#8]
After updating `mssql@6.3.1` to `mssql@7.1.3` I realized that I cannot connect. Module `mssql` started using `@tedious/connection-string` to handle connection string parsing (this one) and by that move it cannot parse URI type connection strings that are some kind of a standard in NodeJS for connections.

This move was intentional? I couldn't find any comment around it. Thank you!

**Comment by dhensby** [comment]
This is correct, at the moment there is no support for connection URIs. This library is designed to be a [Connection String](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings) parser. Whilst it may be worth adding a more generic URI style parser too, it's not currently planned as there doesn't appear to be any kind of proper standard for it, especially with MSSQL contexts.

**Comment by mstrujic-cls** [comment]
Can we at least expose that existing file that was part of `mssql` module that was used before as an additional "helper" if someone wants to continue using it? 

I am talking about:
https://github.com/tediousjs/node-mssql/blob/master/lib/connectionstring.js

**Comment by dhensby** [comment]
This is the wrong repo for that request. but one can use it already by accessing it directly. That won't be removed until v8.

Of course, PRs to this repo could be made to add support for connection URIs.

Part of my hesitancy for adding connection URIs is there's no standard for them and I can't find any reference to where one would obtain a connection URI to even begin basing a pseudo-standard on. With MSSQL the connection strings are produced by the server and there's a clear spec so this is a fixed problem to solve, but there is no such fixed remit to connection URIs.
